"""Private, read-only Chucky Lab cockpit dashboard."""

# Candidate text is deliberately not rendered here.  During an active v3.3
# round peers must not learn one another's proposals through the operational UI.
COCKPIT_HTML = r"""<!doctype html>
<html><head><title>Chucky Lab</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:dark;font-family:system-ui}body{margin:0;background:#07101b;color:#e8f0fb}main{max-width:1440px;margin:auto;padding:22px}.top{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.top h1{margin:0;font-size:24px}.controls{margin-left:auto;display:flex;gap:8px;flex-wrap:wrap}input,button{background:#101f33;color:#e8f0fb;border:1px solid #315071;border-radius:8px;padding:9px}button{background:#2869d8;font-weight:700;cursor:pointer}.grid{display:grid;gap:14px;margin-top:16px;grid-template-columns:repeat(auto-fit,minmax(290px,1fr))}.card,.panel{background:#0f1b2d;border:1px solid #263e5b;border-radius:12px;padding:15px}.card h2,.panel h2{font-size:14px;margin:0 0 12px}.line{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #203650;padding:8px 0;font-size:13px}.tag{padding:3px 7px;border-radius:999px;font-weight:700;font-size:11px;background:#203959;color:#b9d4ff}.tag.running,.tag.ready,.tag.completed,.tag.active{background:#153c36;color:#7ee8c1}.tag.error,.tag.failed,.tag.invalid,.tag.stale{background:#4e2130;color:#ffabb7}.tag.pending,.tag.blocked{background:#453a1d;color:#ffe28b}.muted,.empty{color:#9cadc7}.label{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#9cadc7}ul{list-style:none;padding:0;margin:0}li{padding:9px 0;border-top:1px solid #203650;font-size:13px}code{color:#b7d0ff;word-break:break-all}.summary{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}.metric{min-width:130px}.metric b{font-size:20px}
</style></head><body><main>
<header class="top"><div><h1>CHUCKY LAB <span class="muted">/ GPU-LAB</span></h1><div id="subtitle" class="muted">Choose a Research OS project</div></div><div class="controls"><input id="project" placeholder="Research project ID"><button id="load">Open cockpit</button><button id="autopilot" disabled>AUTOPILOT</button><button id="continue" disabled>AUTO CONTINUE</button><button id="pause" disabled>PAUSE LAB</button></div></header>
<section id="summary" class="summary"><span class="empty">No project loaded.</span></section>
<section class="grid"><article class="panel"><h2>DISCOVERY ROUNDS</h2><ul id="discovery"></ul></article><article class="panel"><h2>DISCOVERY SYNTHESIS</h2><ul id="archives"></ul></article><article class="panel"><h2>ACTIVE WORKERS</h2><ul id="workers"></ul></article><article class="panel"><h2>SCIENTIFIC GATES</h2><ul id="gates"></ul></article><article class="panel"><h2>GPU JOBS</h2><ul id="gpus"></ul></article><article class="panel"><h2>READY WORK</h2><ul id="ready"></ul></article><article class="panel"><h2>RECENT EVENTS</h2><ul id="events"></ul></article><article class="panel"><h2>WORKER TURNS</h2><ul id="turns"></ul></article></section>
</main><script>
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])),tag=v=>`<span class="tag ${esc(String(v||'').toLowerCase())}">${esc(v||'UNKNOWN')}</span>`;
let projectId=new URLSearchParams(location.search).get('project_id')||'',csrfToken='',controls={};$('#project').value=projectId;
const list=(items,render,empty)=>items?.length?items.map(render).join(''):`<li class="empty">${empty}</li>`;
function render(data){const s=data.lab_state||{},c=data.controls||{};$('#subtitle').textContent=`${s.project?.name||'Project'} · ${s.project?.id||projectId}`;$('#summary').innerHTML=[['AUTOPILOT',c.autopilot_enabled?'ON':'OFF'],['AUTO CONTINUE',c.auto_continue_enabled?'ON':'OFF'],['SCHEDULING',c.paused?'PAUSED':'ACTIVE'],['READY WORK',(s.ready_work_items||[]).length],['DISCOVERY ROUNDS',(data.discovery_rounds||[]).length],['GPU RUNS',(s.gpu_activity||[]).length]].map(([a,b])=>`<article class="card metric"><div class="label">${a}</div><b>${esc(b)}</b></article>`).join('');$('#discovery').innerHTML=list(data.discovery_rounds,r=>`<li>${tag(r.status)} <b>${esc(r.search_regime||'UNSPECIFIED')}</b><br><span class="muted">${esc(r.phase)} · peer ideas: ${esc(r.peer_visibility)}</span><br><code>${esc(r.id)}</code></li>`,'No durable discovery rounds.');$('#workers').innerHTML=list(s.active_workers,w=>`<li>${tag(w.status)} <b>${esc(w.display_name||w.worker_id)}</b><br><span class="muted">${esc(w.active_role||'IDLE')} · ${esc(w.last_heartbeat_at||'no heartbeat')}</span></li>`,'No active workers.');$('#gates').innerHTML=list(s.scientific_gates,g=>`<li>${tag(g.status)} <b>${esc(g.gate_key)}</b><br><code>${esc(g.authority_key)}</code></li>`,'No active gates.');$('#gpus').innerHTML=list(s.gpu_activity,x=>`<li>${tag(x.status)} <code>${esc(x.id)}</code><br>${esc(x.data?.label||x.data?.job_id||'ExperimentRun')}</li>`,'No active GPU execution.');$('#ready').innerHTML=list(s.ready_work_items,x=>`<li>${tag(x.scientific_role)} <b>${esc(x.title)}</b><br><span class="muted">priority ${esc(x.priority)}</span></li>`,'No useful work is ready.');$('#events').innerHTML=list(s.recent_events,x=>`<li>${esc(x.event_type)}<br><span class="muted">${esc(x.created_at||'')}</span></li>`,'No recent events.');$('#turns').innerHTML=list(data.recent_turns,x=>`<li>${tag(x.outcome)} ${esc(x.summary||'No summary')}<br><span class="muted">${esc(x.created_at||'')}</span></li>`,'No worker turns recorded.');renderControls(c)}
function renderArchives(items){$('#archives').innerHTML=list(items,a=>`<li><b>${esc(a.coverage?.portfolio_health||'ARCHIVED')}</b> · niches ${esc(a.coverage?.effective_niche_count)}<br>${(a.candidates||[]).map(x=>`${x.selected?'★ ':x.runner_up?'↳ ':''}${esc(x.title)} [${esc(x.scientific_distance)} / ${esc(x.mechanistic_niche)}]`).join('<br>')}</li>`,'Candidate detail appears only after synthesis.')}
function renderControls(next){controls=next;for(const id of ['autopilot','continue','pause'])$('#'+id).disabled=false;$('#autopilot').textContent=`AUTOPILOT ${next.autopilot_enabled?'ON':'OFF'}`;$('#continue').textContent=`AUTO CONTINUE ${next.auto_continue_enabled?'ON':'OFF'}`;$('#pause').textContent=next.paused?'RESUME LAB':'PAUSE LAB'}
async function setControl(update){if(!projectId||!csrfToken)return;const r=await fetch('/cockpit/controls',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrfToken},body:JSON.stringify({project_id:projectId,...update})});if(!r.ok)throw Error((await r.json()).error||'Control update failed');await load()}
async function load(){projectId=$('#project').value.trim();if(!projectId)return;history.replaceState(null,'',`/?project_id=${encodeURIComponent(projectId)}`);try{const r=await fetch(`/cockpit/state?project_id=${encodeURIComponent(projectId)}`),data=await r.json();if(!r.ok)throw Error(data.error||'Could not load cockpit');render(data);renderArchives(data.discovery_archives||[])}catch(e){$('#subtitle').textContent=e.message}}
$('#load').onclick=load;$('#project').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('#autopilot').onclick=()=>setControl({autopilot_enabled:!controls.autopilot_enabled}).catch(e=>$('#subtitle').textContent=e.message);$('#continue').onclick=()=>setControl({auto_continue_enabled:!controls.auto_continue_enabled}).catch(e=>$('#subtitle').textContent=e.message);$('#pause').onclick=()=>setControl({paused:!controls.paused}).catch(e=>$('#subtitle').textContent=e.message);fetch('/cockpit/session').then(r=>r.json()).then(x=>csrfToken=x.csrf_token||'');if(projectId)load();setInterval(()=>{if(projectId)load()},5000);
</script></body></html>"""
