DASHBOARD_HTML = """<!doctype html>
<html><head><title>GPU Lab MCP</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif}body{margin:0;background:#09111f;color:#e7edf7}main{max-width:1180px;margin:auto;padding:32px 20px}h1{margin:0;font-size:28px}h2{margin-top:28px}.sub,.muted{color:#9fb0c8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin:18px 0}.card,.panel{background:#111d30;border:1px solid #253958;border-radius:12px;padding:18px}.label{font-size:12px;text-transform:uppercase;color:#8da1c0;letter-spacing:.08em}.value{font-size:20px;font-weight:700;margin-top:7px}table{width:100%;border-collapse:collapse;background:#111d30;border:1px solid #253958;border-radius:12px;overflow:hidden}th,td{text-align:left;padding:12px;border-bottom:1px solid #203451;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#8da1c0}.badge{border-radius:99px;padding:3px 8px;font-size:12px;font-weight:700}.running{background:#173c63;color:#8bc5ff}.queued{background:#443514;color:#ffe08a}.completed,.success{background:#123e2a;color:#73e7a1}.failed,.unknown,.failure{background:#4b1d2a;color:#ff9ca8}code{white-space:pre-wrap;color:#c6d7f4}#updated{float:right;color:#8da1c0;font-size:13px}.metric{display:grid;gap:8px;margin:15px 0}.metric-head{display:flex;justify-content:space-between;gap:12px;font-size:13px}.bar{height:9px;background:#07101d;border-radius:999px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#3d76ee,#51d88a);border-radius:inherit}.bar.memory i{background:linear-gradient(90deg,#9b6cff,#e18bff)}.map-controls{display:flex;gap:9px;margin:13px 0}.map-controls input{flex:1;min-width:0;background:#09111f;border:1px solid #38537c;border-radius:8px;color:#e7edf7;padding:10px}.map-controls button{background:#3d76ee;color:#fff;border:0;border-radius:8px;font-weight:700;padding:10px 15px;cursor:pointer}.map-canvas{min-height:160px;background:#070d18;border:1px solid #253958;border-radius:10px;padding:14px;overflow:auto}.map-empty{color:#9fb0c8}.node{display:inline-block;margin:5px;padding:7px;border-radius:8px;background:#1a304e;color:#dbe8ff;font-size:13px}
</style></head><body><main><span id="updated">Connecting...</span><h1>GPU Lab MCP</h1><p class="sub">Live local experiment monitor refreshes every five seconds.</p>
<section class="grid" id="gpus"></section>
<section class="panel"><h2>Live experiments</h2><p class="sub">These are durable local job records. A completed or failed status means the job has finished.</p><table><thead><tr><th>Job</th><th>Status</th><th>Started</th><th>Exit</th></tr></thead><tbody id="jobs"><tr><td colspan="4">Loading...</td></tr></tbody></table></section>
<section class="panel"><h2>Research Map</h2><p class="sub">Evidence-linked WorldModel entities and causal edges.</p><div class="map-controls"><input id="project-id" placeholder="Research project ID"><button id="load-map">Load map</button></div><div class="map-canvas" id="map"><div class="map-empty">Enter a research project ID to load its WorldModel.</div></div></section>
<h2>Recent activity</h2><table><thead><tr><th>Time</th><th>Action</th><th>Outcome</th><th>Duration</th><th>Arguments / error</th></tr></thead><tbody id="activity"><tr><td colspan="5">Loading...</td></tr></tbody></table></main>
<script>
const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const pct=(v,max)=>Math.max(0,Math.min(100,max?Math.round(v/max*100):0));
function card(title,detail,sub){return `<article class="card"><div class="label">${esc(title)}</div><div class="value">${esc(detail||'Unavailable')}</div><div class="sub">${esc(sub||'')}</div></article>`}
function gpuCard(g){const memory=pct(g.memory_used_mb,g.memory_total_mb);return `<article class="card"><div class="label">GPU ${esc(g.index)} · ${esc(g.name)}</div><div class="value">${esc(g.utilization_percent)}% compute <span class="muted">${esc(g.temperature_c)}°C</span></div><div class="metric"><div class="metric-head"><span>GPU utilization</span><span>${esc(g.utilization_percent)}%</span></div><div class="bar"><i style="width:${pct(g.utilization_percent,100)}%"></i></div></div><div class="metric"><div class="metric-head"><span>GPU memory</span><span>${esc(g.memory_used_mb)} / ${esc(g.memory_total_mb)} MiB</span></div><div class="bar memory"><i style="width:${memory}%"></i></div></div></article>`}
function renderMonitor(m){const cards=(m.gpus||[]).map(gpuCard);if(m.gpu_error)cards.push(card('Local GPU telemetry','Unavailable',m.gpu_error));document.querySelector('#gpus').innerHTML=cards.join('')||card('Local GPU','No telemetry available',m.enabled?'':'Local runner is disabled');document.querySelector('#jobs').innerHTML=(m.jobs||[]).map(j=>`<tr><td><b>${esc(j.name||j.job_id)}</b><br><code>${esc(j.job_id)}</code></td><td><span class="badge ${esc(j.status)}">${esc(j.status)}</span></td><td>${esc(j.started_at?new Date(j.started_at).toLocaleString():'—')}</td><td>${esc(j.exit_code??'—')}</td></tr>`).join('')||'<tr><td colspan="4">No local jobs recorded.</td></tr>'}
async function loadMap(){const projectId=document.querySelector('#project-id').value.trim(),map=document.querySelector('#map');if(!projectId){map.innerHTML='<div class="map-empty">Enter a research project ID first.</div>';return}map.innerHTML='<div class="map-empty">Loading WorldModel…</div>';try{const r=await fetch('/research-map?project_id='+encodeURIComponent(projectId)),data=await r.json();if(!r.ok)throw new Error(data.error||'Could not load research map');const nodes=(data.nodes||[]).map(n=>`<span class="node">${esc(n.data?.name||n.kind)}</span>`).join('');map.innerHTML=nodes||'<div class="map-empty">This WorldModel has no entities yet.</div>'}catch(e){map.innerHTML=`<div class="map-empty">${esc(e.message)}</div>`}}
async function refresh(){try{const [activity,monitor]=await Promise.all([fetch('/activity').then(r=>r.json()),fetch('/monitor').then(r=>r.json())]);renderMonitor(monitor);document.querySelector('#activity').innerHTML=activity.map(x=>`<tr><td>${esc(new Date(x.at).toLocaleString())}</td><td><b>${esc(x.tool)}</b></td><td><span class="badge ${x.outcome==='success'?'success':'failure'}">${esc(x.outcome)}</span></td><td>${esc(x.duration_ms)} ms</td><td><code>${esc(x.error||JSON.stringify(x.arguments))}</code></td></tr>`).join('')||'<tr><td colspan="5">No activity yet.</td></tr>';updated.textContent='Updated '+new Date().toLocaleTimeString()}catch(e){updated.textContent='Connection error: '+e}}
document.querySelector('#load-map').onclick=loadMap;const initial=new URLSearchParams(location.search).get('project_id');if(initial){document.querySelector('#project-id').value=initial;loadMap()}refresh();setInterval(refresh,5000);
</script></body></html>"""
