DASHBOARD_HTML = """<!doctype html>
<html><head><title>GPU Lab MCP</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif}body{margin:0;background:#09111f;color:#e7edf7}main{max-width:1180px;margin:auto;padding:32px 20px}h1{margin:0;font-size:28px}.sub{color:#9fb0c8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin:24px 0}.card,.panel{background:#111d30;border:1px solid #253958;border-radius:12px;padding:18px}.label{font-size:12px;text-transform:uppercase;color:#8da1c0;letter-spacing:.08em}.value{font-size:20px;font-weight:700;margin-top:7px}.ok{color:#51d88a}.error{color:#ff8391}table{width:100%;border-collapse:collapse;background:#111d30;border:1px solid #253958;border-radius:12px;overflow:hidden}th,td{text-align:left;padding:12px;border-bottom:1px solid #203451;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#8da1c0}.badge{border-radius:99px;padding:3px 8px;font-size:12px;font-weight:700}.success{background:#123e2a;color:#73e7a1}.failure{background:#4b1d2a;color:#ff9ca8}code{white-space:pre-wrap;color:#c6d7f4}#updated{float:right;color:#8da1c0;font-size:13px}.map-controls{display:flex;gap:9px;margin:13px 0}.map-controls input{flex:1;min-width:0;background:#09111f;border:1px solid #38537c;border-radius:8px;color:#e7edf7;padding:10px}.map-controls button{background:#3d76ee;color:#fff;border:0;border-radius:8px;font-weight:700;padding:10px 15px;cursor:pointer}.map-layout{display:grid;grid-template-columns:minmax(0,1fr) 245px;gap:14px}.map-canvas{min-height:430px;background:#070d18;border:1px solid #253958;border-radius:10px;overflow:hidden}.map-canvas svg{width:100%;height:430px;display:block}.map-empty{color:#9fb0c8;padding:24px}.edge{stroke-width:2;opacity:.8}.edge-label{font-size:10px;fill:#aabbd5}.node{cursor:pointer}.node circle{stroke:#dbe8ff;stroke-width:1.5}.node text{fill:#e7edf7;font-size:12px;pointer-events:none}.legend{display:grid;gap:8px;font-size:13px;color:#c6d7f4}.swatch{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:7px}.inspector{min-height:180px;white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:760px){.map-layout{grid-template-columns:1fr}.map-controls{flex-direction:column}}
</style></head><body><main><span id="updated">Connecting...</span><h1>GPU Lab MCP</h1><section class="grid" id="gpus"></section>
<section class="panel"><h2>Research Map</h2><p class="sub">Evidence-linked WorldModel entities and causal edges. Select a node to inspect its scientific provenance.</p><div class="map-controls"><input id="project-id" placeholder="Research project ID"><button id="load-map">Load map</button></div><div class="map-layout"><div class="map-canvas" id="map"><div class="map-empty">Enter a research project ID to load its WorldModel.</div></div><aside class="panel inspector" id="inspector">Select a node or edge.</aside></div></section>
<h2>Recent activity</h2><table><thead><tr><th>Time</th><th>Action</th><th>Outcome</th><th>Duration</th><th>Arguments / error</th></tr></thead><tbody id="activity"><tr><td colspan="5">Loading...</td></tr></tbody></table></main>
<script>
const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const colors={ScientificVariable:'#60a5fa',Phenomenon:'#f59e0b',Mechanism:'#d946ef',MechanismState:'#2dd4bf',InformationPath:'#a3e635',Assumption:'#fb7185',Scope:'#94a3b8',Intervention:'#f97316',ExpectedEffect:'#8b5cf6'};
const edgeColors={OBSERVED_ASSOCIATION:'#60a5fa',HYPOTHESIZED_CAUSAL:'#f59e0b',INTERVENTION_SUPPORTED:'#34d399',WEAKENED:'#fb7185',REFUTED:'#ef4444',UNKNOWN:'#94a3b8'};
function gpuCard(title,detail,sub){return `<article class="card"><div class="label">${esc(title)}</div><div class="value">${esc(detail||'Unavailable')}</div><div class="sub">${esc(sub||'')}</div></article>`}
function detail(title,data){inspector.innerHTML=`<div class="label">${esc(title)}</div><h3>${esc(data.name||data.relation||data.kind||'Research object')}</h3><p>${esc(data.description||data.rationale||'No description recorded.')}</p><code>${esc(JSON.stringify(data.attributes||data,null,2))}</code>`}
function position(index,total){const angle=(Math.PI*2*index/Math.max(total,1))-Math.PI/2;const radius=Math.min(160,55+total*8);return{x:300+Math.cos(angle)*radius,y:215+Math.sin(angle)*radius}}
function renderMap(graph){const nodes=graph.nodes||[],edges=graph.edges||[];if(!nodes.length){map.innerHTML='<div class="map-empty">This WorldModel has no entities yet. Add evidence-linked entities and causal edges through MCP, then reload.</div>';return}const pos=new Map(nodes.map((n,i)=>[String(n.id),position(i,nodes.length)]));const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 430');for(const edge of edges){const d=edge.data||{},a=pos.get(String(d.source_id)),b=pos.get(String(d.target_id));if(!a||!b)continue;const line=document.createElementNS(ns,'line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class','edge');line.setAttribute('stroke',edgeColors[d.edge_status]||edgeColors.UNKNOWN);line.onclick=()=>detail('Causal edge',d);svg.append(line);const label=document.createElementNS(ns,'text');label.setAttribute('x',(a.x+b.x)/2);label.setAttribute('y',(a.y+b.y)/2-5);label.setAttribute('class','edge-label');label.textContent=d.relation||'RELATES_TO';svg.append(label)}for(const node of nodes){const d=node.data||{},p=pos.get(String(node.id)),g=document.createElementNS(ns,'g');g.setAttribute('class','node');g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.onclick=()=>detail(node.kind,d);const circle=document.createElementNS(ns,'circle');circle.setAttribute('r','15');circle.setAttribute('fill',colors[node.kind]||'#64748b');const text=document.createElementNS(ns,'text');text.setAttribute('x','20');text.setAttribute('y','4');text.textContent=(d.name||node.kind||'Node').slice(0,32);g.append(circle,text);svg.append(g)}map.replaceChildren(svg);inspector.innerHTML=`<div class="label">WorldModel</div><h3>${esc(graph.world_model?.data?.name||'Research map')}</h3><p>${nodes.length} entities · ${edges.length} causal edges</p><div class="legend">${Object.entries(edgeColors).map(([s,c])=>`<span><i class="swatch" style="background:${c}"></i>${esc(s)}</span>`).join('')}</div>`}
async function loadMap(){const projectId=document.querySelector('#project-id').value.trim();if(!projectId){map.innerHTML='<div class="map-empty">Enter a research project ID first.</div>';return}map.innerHTML='<div class="map-empty">Loading WorldModel…</div>';try{const r=await fetch('/research-map?project_id='+encodeURIComponent(projectId));const payload=await r.json();if(!r.ok)throw new Error(payload.error||'Could not load research map');history.replaceState(null,'','?project_id='+encodeURIComponent(projectId));renderMap(payload)}catch(e){map.innerHTML=`<div class="map-empty">${esc(e.message)}</div>`}}
async function refresh(){try{const [status,activity]=await Promise.all([fetch('/status').then(r=>r.json()),fetch('/activity').then(r=>r.json())]);let cards=[];for(const i of status.instances||[])cards.push(gpuCard('Vast GPU',i.gpu_model,`${i.id} - ${i.status} - $${i.hourly_price||'?'} / hr`));const l=status.local;if(l)cards.push(gpuCard('Local GPU',l.gpu,l.workspace));document.querySelector('#gpus').innerHTML=cards.join('')||gpuCard('Gateway','No GPUs found','');document.querySelector('#activity').innerHTML=activity.map(x=>`<tr><td>${esc(new Date(x.at).toLocaleString())}</td><td><b>${esc(x.tool)}</b></td><td><span class="badge ${x.outcome==='success'?'success':'failure'}">${esc(x.outcome)}</span></td><td>${esc(x.duration_ms)} ms</td><td><code>${esc(x.error||JSON.stringify(x.arguments))}</code></td></tr>`).join('')||'<tr><td colspan="5">No activity yet.</td></tr>';updated.textContent='Updated '+new Date().toLocaleTimeString()}catch(e){updated.textContent='Connection error: '+e}}
document.querySelector('#load-map').onclick=loadMap;const initial=new URLSearchParams(location.search).get('project_id');if(initial){document.querySelector('#project-id').value=initial;loadMap()}refresh();setInterval(refresh,15000);
</script></body></html>"""
